/* TRIGGERS NOMS MAJUSCULE */
CREATE OR REPLACE TRIGGER PROJET_UpperCaseAdherentName
BEFORE INSERT OR UPDATE ON PROJET_ADHERENT
FOR EACH ROW
BEGIN
	:new.nom := UPPER(:new.nom);
END;
/
CREATE OR REPLACE TRIGGER PROJET_UpperCaseAnimateurName
BEFORE INSERT OR UPDATE ON PROJET_ANIMATEUR
FOR EACH ROW
BEGIN
	:new.nom := UPPER(:new.nom);
END;
/
/* TRIGGERS INCRÉMENTATION CLÉ PRIMAIRE */

CREATE OR REPLACE TRIGGER T_PROJET_ANIMATEUR_PK
BEFORE INSERT ON PROJET_ANIMATEUR
FOR EACH ROW
BEGIN
   SELECT seq_PROJET_ANIMATEUR_pk.nextval INTO :new.id_animateur FROM dual;
END;
/
CREATE OR REPLACE TRIGGER T_PROJET_ADHERENT_PK
BEFORE INSERT ON PROJET_ADHERENT
FOR EACH ROW
BEGIN
   SELECT seq_PROJET_ADHERENT_pk.nextval INTO :new.id_adherent FROM dual;
END;
/
CREATE OR REPLACE TRIGGER T_PROJET_ACTIVITE_PK
BEFORE INSERT ON PROJET_ACTIVITE
FOR EACH ROW
BEGIN
   SELECT seq_PROJET_ACTIVITE_pk.nextval INTO :new.id_activite FROM dual;
END;

